from pydantic import BaseModel, Field
from typing import List, Optional, Any, Dict
from enum import Enum

# --- StoryFlag ---
class StoryFlagBase(BaseModel):
    flag_name: str
    value: str
class StoryFlag(StoryFlagBase):
    id: int
    class Config:
        from_attributes = True

# --- ActiveQuest ---
class ActiveQuestBase(BaseModel):
    title: str
    description: Optional[str] = None
    steps: List[str]
    current_step: int = 1
    status: str = "active"
    campaign_id: int
class ActiveQuestCreate(ActiveQuestBase):
    pass
class ActiveQuest(ActiveQuestBase):
    id: int
    class Config:
        from_attributes = True
class ActiveQuestUpdate(BaseModel):
    current_step: Optional[int] = None
    status: Optional[str] = None
    description: Optional[str] = None
    steps: Optional[List[str]] = None

# --- Campaign ---
class CampaignBase(BaseModel):
    name: str
    main_plot_summary: Optional[str] = None
class CampaignCreate(CampaignBase):
    pass
class Campaign(CampaignBase):
    id: int
    active_quests: List[ActiveQuest] = []
    class Config:
        from_attributes = True

# --- Orchestration ---
class OrchestrationSpawnNpc(BaseModel):
    template_id: str
    location_id:int
    name_override: Optional[str] = None
    coordinates: Optional[Any] = None
    current_hp: Optional[int] = None
    max_hp: Optional[int] = None
    temp_hp: Optional[int] = 0
    max_composure: Optional[int] = 10
    current_composure: Optional[int] = 10
    resource_pools: Optional[Dict[str, Any]] = {}
    abilities: Optional[List[str]] = []
    behavior_tags: Optional[List[str]] = []

class TrapInstanceCreate(BaseModel):
    template_id: str
    location_id: int
    coordinates: List[int]

class OrchestrationSpawnItem(BaseModel):
    template_id: str
    location_id: Optional[int] = None
    npc_id: Optional[int] = None
    quantity: int = 1
    coordinates: Optional[Any] = None

class OrchestrationCharacterContext(BaseModel):
    id: int
    name: str
    kingdom: str
    character_sheet: Dict[str, Any]

class OrchestrationWorldContext(BaseModel):
    id: int
    name: str
    region: Any
    generated_map_data: Optional[Any] = None
    ai_annotations: Optional[Dict[str, Any]] = None
    spawn_points: Optional[Dict[str, Any]] = None
    npcs: List[Any] = []
    items: List[Any] = []

# --- Combat ---
class CombatStartRequest(BaseModel):
    location_id: int
    player_ids: List[str]
    npc_template_ids: List[str]

class CombatParticipantResponse(BaseModel):
    actor_id: str
    actor_type: str
    initiative_roll: int
    # --- BURT'S NEW FIELD ---
    ability_usage: Dict[str, int] = {}
    # ------------------------
    class Config:
        from_attributes = True

class CombatEncounter(BaseModel):
    id: int
    location_id: int
    status: str
    turn_order: List[str]
    current_turn_index: int
    participants: List[CombatParticipantResponse] = []
    # --- BURT'S NEW FIELD ---
    active_zones: List[Dict[str, Any]] = []
    # ------------------------
    class Config:
        from_attributes = True

class PlayerActionRequest(BaseModel):
    action: str
    target_id: Optional[str] = None
    ability_id: Optional[str] = None
    item_id: Optional[str] = None
    coordinates: Optional[List[int]] = None
    ready_action_details: Optional[Dict[str, Any]] = None

class PlayerActionResponse(BaseModel):
    success: bool
    message: str
    log: list[str]
    new_turn_index: int
    combat_over: bool = False
    # --- BURT'S NEW FIELD ---
    reaction_opportunity: Optional[Dict[str, Any]] = None
    # ------------------------

class InteractionRequest(BaseModel):
    actor_id: str
    target_object_id: str
    location_id: int
    interaction_type: str = "use"

class InteractionResponse(BaseModel):
    success: bool
    message: str
    updated_annotations: Optional[Dict[str, Any]] = None
    items_added: Optional[List[Dict[str, Any]]] = None
    items_removed: Optional[List[Dict[str, Any]]] = None


# ============================================================================
# REACTIVE STORY ENGINE - Event System
# ============================================================================

class EventTriggerType(str, Enum):
    """Defines the category of trigger this event addresses."""
    REPUTATION_CHANGE = "REPUTATION_CHANGE"
    RESOURCE_LOW = "RESOURCE_LOW"
    COMBAT_CRITICAL = "COMBAT_CRITICAL"
    PLAYER_ACTION = "PLAYER_ACTION"


class EventConsequenceType(str, Enum):
    """Defines the type of action the game client should take."""
    SPAWN_NPC = "SPAWN_NPC"
    INITIATE_SKILL_CHALLENGE = "INITIATE_SKILL_CHALLENGE"
    ADD_QUEST_LOG = "ADD_QUEST_LOG"
    WORLD_STATE_CHANGE = "WORLD_STATE_CHANGE"


class StoryEvent(BaseModel):
    """
    A specific event payload generated by the Event Engine.
    """
    event_id: str = Field(..., description="Unique ID for this type of narrative event (e.g., 'bandit_ambush').")
    trigger_type: EventTriggerType
    consequence_type: EventConsequenceType
    narrative_text: str = Field(..., description="The main text describing the event to the user.")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary data needed to execute the consequence (e.g., NPC ID, challenge difficulty).")


class WorldStateContext(BaseModel):
    """
    Minimal context required by the event generation logic.
    Populated by the Orchestrator before calling the Event Engine.
    """
    player_reputation: int = Field(..., description="Player's current reputation score.")
    kingdom_resource_level: int = Field(..., description="Current resource level of a key world entity.")
    last_combat_outcome: Optional[str] = Field(None, description="E.g., 'CRITICAL_HIT', 'DEFEAT'.")
    current_location_tags: List[str] = Field(default_factory=list, description="Tags like ['forest', 'ruins'].")
