# Pydantic schemas for AI Dungeon Master responses

from pydantic import BaseModel, Field
from typing import List, Optional

class NarrativeResponse(BaseModel):
    """Schema for a narrative response from the AI DM.
    The response should be a short paragraph describing the outcome.
    """
    success: bool = Field(..., description="Indicates if the AI generated a valid response")
    message: str = Field(..., description="The narrative text generated by the AI")
    # Optional additional data can be added in the future

class DialogueResponse(BaseModel):
    """Schema for NPC dialogue generated by the AI DM.
    Includes the spoken line and an optional action flag.
    """
    success: bool = Field(..., description="Indicates if the AI generated a valid response")
    dialogue: str = Field(..., description="The NPC's spoken line")
    next_action: Optional[str] = Field(None, description="Suggested next action for the player or NPC")
