"""initial_schema

Revision ID: 2f36b11650e3
Revises: 
Create Date: 2025-11-27 16:03:08.851779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f36b11650e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_reputation', sa.Integer(), nullable=False),
    sa.Column('kingdom_resource_level', sa.Integer(), nullable=False),
    sa.Column('last_map_flavor_context', sa.JSON(), nullable=True),
    sa.Column('last_event_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_map_id', sa.Integer(), nullable=True),
    sa.Column('grid_width', sa.Integer(), nullable=True),
    sa.Column('grid_height', sa.Integer(), nullable=True),
    sa.Column('layers', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_id'), 'maps', ['id'], unique=False)
    op.create_index(op.f('ix_maps_name'), 'maps', ['name'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_weather', sa.String(), nullable=True),
    sa.Column('environmental_effects', sa.JSON(), nullable=True),
    sa.Column('faction_influence', sa.JSON(), nullable=True),
    sa.Column('kingdom_resource_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_campaign_id'), 'regions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('exits', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generated_map_data', sa.JSON(), nullable=True),
    sa.Column('map_seed', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('ai_annotations', sa.JSON(), nullable=True),
    sa.Column('spawn_points', sa.JSON(), nullable=True),
    sa.Column('flavor_context', sa.JSON(), nullable=True),
    sa.Column('player_reputation', sa.Integer(), nullable=True),
    sa.Column('last_combat_outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_campaign_id'), 'locations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('z', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('nested_map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['nested_map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiles_id'), 'tiles', ['id'], unique=False)
    op.create_table('npc_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('name_override', sa.String(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('temp_hp', sa.Integer(), nullable=True),
    sa.Column('max_composure', sa.Integer(), nullable=True),
    sa.Column('current_composure', sa.Integer(), nullable=True),
    sa.Column('resource_pools', sa.JSON(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('injuries', sa.JSON(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('behavior_tags', sa.JSON(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_instances_id'), 'npc_instances', ['id'], unique=False)
    op.create_index(op.f('ix_npc_instances_template_id'), 'npc_instances', ['template_id'], unique=False)
    op.create_table('trap_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trap_instances_id'), 'trap_instances', ['id'], unique=False)
    op.create_index(op.f('ix_trap_instances_status'), 'trap_instances', ['status'], unique=False)
    op.create_index(op.f('ix_trap_instances_template_id'), 'trap_instances', ['template_id'], unique=False)
    op.create_table('item_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_instances_id'), 'item_instances', ['id'], unique=False)
    op.create_index(op.f('ix_item_instances_template_id'), 'item_instances', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_instances_template_id'), table_name='item_instances')
    op.drop_index(op.f('ix_item_instances_id'), table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_index(op.f('ix_trap_instances_template_id'), table_name='trap_instances')
    op.drop_index(op.f('ix_trap_instances_status'), table_name='trap_instances')
    op.drop_index(op.f('ix_trap_instances_id'), table_name='trap_instances')
    op.drop_table('trap_instances')
    op.drop_index(op.f('ix_npc_instances_template_id'), table_name='npc_instances')
    op.drop_index(op.f('ix_npc_instances_id'), table_name='npc_instances')
    op.drop_table('npc_instances')
    op.drop_index(op.f('ix_tiles_id'), table_name='tiles')
    op.drop_table('tiles')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_campaign_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_campaign_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_maps_name'), table_name='maps')
    op.drop_index(op.f('ix_maps_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_table('game_state')
    # ### end Alembic commands ###
