"""Initial simulation schema clean

Revision ID: b1745e6686dd
Revises:
Create Date: 2025-11-25 00:13:01.452528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1745e6686dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('relationship_matrix', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_id'), 'factions', ['id'], unique=False)
    op.create_index(op.f('ix_factions_name'), 'factions', ['name'], unique=True)
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_tension', sa.Integer(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_state_id'), 'world_state', ['id'], unique=False)
    op.create_table('world_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('owner_faction_id', sa.Integer(), nullable=True),
    sa.Column('abundance_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_resources_id'), 'world_resources', ['id'], unique=False)
    op.create_index(op.f('ix_world_resources_type'), 'world_resources', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_resources_type'), table_name='world_resources')
    op.drop_index(op.f('ix_world_resources_id'), table_name='world_resources')
    op.drop_table('world_resources')
    op.drop_index(op.f('ix_world_state_id'), table_name='world_state')
    op.drop_table('world_state')
    op.drop_index(op.f('ix_factions_name'), table_name='factions')
    op.drop_index(op.f('ix_factions_id'), table_name='factions')
    op.drop_table('factions')
    # ### end Alembic commands ###
